INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(1,'B772LR','-2000.0','35.04', 'TMAX_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(2,'B772LR','0.0','39.4', 'TMAX_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(3,'B772LR','10000.0','39.4', 'TMAX_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(4,'B772LR','10001.0','34.0', 'TMAX_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(5,'B772LR','36089.0','34.0', 'TMAX_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(6,'B772LR','43100.0','20.0', 'TMAX_F');



INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(7,'B772LR','-2000.0','-81.0', 'TMIN_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(8,'B772LR','0.0','-77.0', 'TMIN_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(9,'B772LR','32000.0','-26.6', 'TMIN_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(10,'B772LR','36089.0','-18.5', 'TMIN_F');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(11,'B772LR','43100.0','-18.5', 'TMIN_F');


INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(12,'B772LR','-2000.0','35.04', 'TMAX_G');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(13,'B772LR','0.0','39.4', 'TMAX_G');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(14,'B772LR','8500.0','39.4', 'TMAX_G');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(15,'B772LR','-2000.0','-73.0', 'TMIN_G');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(16,'B772LR','6500.0','-56.0', 'TMIN_G');

INSERT INTO TEMPERATURE_DEVIATION("ID","AIRCRAFT_ID","ALTITUDE","TEMPERATURE", "AIRCRAFT_TYPE")
VALUES
(17,'B772LR','8500.0','-43.0', 'TMIN_G');
